server:
  port: 9090
spring:
  application:
    name: teach_oa_media
  #rabbitmq的配置
  rabbitmq:
    host: 47.101.34.81
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  datasource:
    druid:
      #      url: jdbc:mysql://localhost:3306/teach_oa?characterEncoding=utf-8&serverTimezone=UTC
      #      username: root
      #      password: zsh
      url: jdbc:mysql://47.101.34.81:3306/teach_oa?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
myconfig:
  mq:
    queue-media-video-processor: teach_queue_media_video_processor  #\u89C6\u9891\u5904\u7406\u961F\u5217
    routingkey-media-video: teach_routingkey_media_video            #\u89C6\u9891\u5904\u7406\u8DEF\u7531
#  m3u8MediaFilePath: D:/test/m3u8MediaFile/
  m3u8MediaFilePath: /usr/local/nginx/html/