spring:
  servlet:
    multipart:
      max-file-size: 1000MB                     #文件最大大小
      max-request-size: 1000MB                  #请求文件最大大小
  application:
    name: teach_oa
  data:
    mongodb:                                  #mongodb配置
      uri: mongodb://47.101.34.81:27017       #mongodb地址
      database: teach_oa                      #mongodb数据库名称
  rabbitmq:
    host: 47.101.34.81
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  datasource:
    druid:
      #      url: jdbc:mysql://localhost:3306/teach_oa?characterEncoding=utf-8&serverTimezone=UTC
      #      username: root
      #      password: zsh
      url: jdbc:mysql://47.101.34.81:3306/teach_oa?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）

  mail:
    username: 1393602726@qq.com                        #邮件提供方的用户名
    password: qrlegzyhqhfmigcb                         #邮件提供方的密码
    host: smtp.qq.com                                  #邮箱服务器
    properties:
      mail.smtp.ssl.enable: true
server:
  port: 8080

myconfig:                                              #自己的配置 由@value读取
#  pdfurl: http://localhost/                           #pdf文件存放的服务器ip
#  pdfPath: D:/test/html/                              #pdf文件存放的具体位置
#  allFilePath: D:/test/allFile/
#  classInfoFileExcel: D:/test/referenceFile/
#  word2PdfFilePath : D:/test/word2PdfFilePath/
#  mediaFilePath: D:/test/mediaFile/
  fastdfsUrl: http://47.101.34.81:8888/                #fastDFS的访问url
  classInfoFileExcel: /root/oaFile/clasInfoFileExcel/   #班级信息导入文件的目录地址
  word2PdfFilePath: /root/oaFile/word2PdfFilePath/    #word转pdf工具 pdf的存放目录
  pdfurl: http://47.101.34.81/                         #pdf文件存放的服务器ip
  pdfPath: /usr/local/nginx/html/                      #pdf文件存放的具体位置 nginx的html文件夹的目录
  allFilePath: /root/oaFile/allFile/                   #所有学生上传的文件根目录
  mediaFilePath: /root/oaFile/mediaFile/
  mq:
    queue-media-video-processor: teach_queue_media_video_processor  #视频处理队列
    routingkey-media-video: teach_routingkey_media_video            #视频处理路由

